

services:
  init:
    build: init
    volumes:
      - ${ENVIRONMENT_ROOT:?error}/:/root_env/

  amavis:
    build: amavis
    restart: always
    volumes:
      - ${ENVIRONMENT_ROOT:?error}/amavis/quarantine/:/var/amavis/quarantine/
      - ${ENVIRONMENT_ROOT:?error}/amavis/clamav/:/var/lib/clamav/
    environment:
      MYDOMAIN: ${MYDOMAIN:?error}
      MAILSERVER_FQDN: ${MAILSERVER_FQDN:?error}
    depends_on:
      init:
        condition: service_completed_successfully
  database:
    build: mariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ${ENVIRONMENT_ROOT:?error}/mysql/data/:/var/lib/mysql/
      - ${ENVIRONMENT_ROOT:?error}/mysql/secrets/:/run/secrets/
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mysql_root
    depends_on:
      init:
        condition: service_completed_successfully
  nextcloud:
    image: nextcloud:fpm-alpine
    restart: always
    ports:
      - "9001:9000"
    volumes:
      - ${ENVIRONMENT_ROOT:?error}/nextcloud/data/:/var/www/html/
      - ${ENVIRONMENT_ROOT:?error}/nextcloud/secrets/:/run/secrets/
    environment:
      MYSQL_HOST: "database"
      MYSQL_PASSWORD_FILE: "/run/secrets/mysql_nextcloud_password"
      MYSQL_DATABASE_FILE: "/run/secrets/mysql_nextcloud_database"
      MYSQL_USER_FILE: "/run/secrets/mysql_nextcloud_user"
    depends_on:
      - database
